version: '2'
services:
  fess:
    build:
      context: ./fess
      args:
        FESS_VERSION: "11.0.1"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    environment:
      ES_HTTP_URL: "http://elasticsearch:9200"
      ES_TRANSPORT_URL: "elasticsearch:9300"
      FESS_DICTIONARY_PATH: "/var/lib/elasticsearch/config/"
    networks:
      - esnet

  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        ELASTIC_VERSION: "5.2.2"
        ES_DOWNLOAD_URL: "https://artifacts.elastic.co/downloads/elasticsearch"
        ES_JAVA_OPTS: "-Xms2g -Xmx2g"
    restart: always
    cap_add:
      - IPC_LOCK
    mem_limit: 4g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/var/lib/elasticsearch
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
    driver: bridge

